modLoader="javafml"
loaderVersion="[52,)"
license="MIT"

[[mods]]
modId="tntexpansion"
version="1.0.0"
displayName="TNT Expansion"
authors="Veilorn"
description='''Adds powerful TNT variants to Minecraft Forge 1.21.1.'''

[[dependencies.tntexpansion]]
modId="forge"
mandatory=true
versionRange="[52,)"
ordering="NONE"
side="BOTH"

[[dependencies.tntexpansion]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
